# Generated by Django 5.0.6 on 2024-06-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0002_rename_data_piblicacao_pergunta_data_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='data_publicacao',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
